CREATE DATABASE VOTACIONES
GO
USE VOTACIONES
GO

CREATE TABLE VOTANTES
(CEDULA BIGINT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
YA_VOTO BIT);
GO

CREATE TABLE CANDIDATOS
(TARJETON INT PRIMARY KEY,
NOMBRE_CANDIDATO VARCHAR(50) NOT NULL,
CANTIDAD_VOTOS INT,
ID_PARTIDO INT NOT NULL);
GO

CREATE TABLE PARTIDOS
(ID_PARTIDO INT PRIMARY KEY,
NOMBRE_PARTIDO VARCHAR(50) NOT NULL,
);
GO

ALTER TABLE CANDIDATOS 
ADD FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDOS(ID_PARTIDO)

INSERT INTO VOTANTES VALUES
(1000001, 'Kevin Andres Jaramillo Hernadez',0 ),
(1000002, 'Laura Martínez',0 ),
(1000003, 'Andrés Gómez',0 ),
(1000004, 'Camila Rivas',0 ),
(1000005, 'Julián Herrera',0 ),
(1000006, 'Valentina Torres',0 ),
(1000007, 'Santiago Ramírez',0 );
GO

INSERT INTO PARTIDOS VALUES
(1, 'Partido Azul'),
(2, 'Partido Amarillo'),
(3, 'Partido Rojo');
GO

INSERT INTO CANDIDATOS VALUES
(10, 'Javier Martínez', 0, 1),
(20, 'Julián Herrera', 0, 2),
(30, 'Valentina Guaido', 0, 3),
(40, 'Kevin Ruiz', 0, 3);
GO


